In [1]:
import os
import numpy as np

from torchvision import datasets, transforms

train_transform = transforms.Compose([transforms.ToTensor()])


In [2]:
# mnist
train_set = datasets.MNIST(
    root="/tmp/mnist", train=True, download=True, transform=train_transform
)
print(list(train_set.data.size()))
print(train_set.data.float().mean() / 255)
print(train_set.data.float().std() / 255)
# [60000, 28, 28]
# tensor(0.1307)
# tensor(0.3081)


[60000, 28, 28]
tensor(0.1307)
tensor(0.3081)


In [3]:
# cifar10
train_set = datasets.CIFAR10(
    root="/tmp/cifar10", train=True, download=True, transform=train_transform
)
print(train_set.data.shape)
print(train_set.data.mean(axis=(0, 1, 2)) / 255)
print(train_set.data.std(axis=(0, 1, 2)) / 255)
# (50000, 32, 32, 3)
# [0.49139968 0.48215841 0.44653091]
# [0.24703223 0.24348513 0.26158784]


(50000, 32, 32, 3)
[0.49139968 0.48215841 0.44653091]
[0.24703223 0.24348513 0.26158784]


In [4]:
# cifar100
train_set = datasets.CIFAR100(
    root="/tmp/cifar100", train=True, download=True, transform=train_transform
)
print(train_set.data.shape)
print(train_set.data.mean(axis=(0, 1, 2)) / 255)
print(train_set.data.std(axis=(0, 1, 2)) / 255)
# (50000, 32, 32, 3)
# [0.50707516 0.48654887 0.44091784]
# [0.26733429 0.25643846 0.27615047]


(50000, 32, 32, 3)
[0.50707516 0.48654887 0.44091784]
[0.26733429 0.25643846 0.27615047]
